set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[1]}]
set_property PACKAGE_PIN J2 [get_ports {ADC_Data[1]}]
set_property PACKAGE_PIN E2 [get_ports {TMDS_Tx_Data_P[1]}]
set_property PACKAGE_PIN D1 [get_ports {TMDS_Tx_Data_P[2]}]
set_property PACKAGE_PIN J3 [get_ports {ADC_Data[0]}]
set_property PACKAGE_PIN H11 [get_ports {ADC_Data[6]}]
set_property PACKAGE_PIN H4 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN J4 [get_ports ADC_En]
set_property IOSTANDARD LVCMOS33 [get_ports ADC_En]
set_property PACKAGE_PIN H12 [get_ports {ADC_Data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[7]}]
set_property PACKAGE_PIN F12 [get_ports {ADC_Data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[4]}]
set_property PACKAGE_PIN C5 [get_ports clk_ADC]
set_property IOSTANDARD LVCMOS33 [get_ports clk_ADC]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ADC_Data[5]}]
set_property PACKAGE_PIN G4 [get_ports TMDS_Tx_Clk_P]
set_property PACKAGE_PIN E12 [get_ports {ADC_Data[3]}]
set_property PACKAGE_PIN G1 [get_ports {TMDS_Tx_Data_P[0]}]
set_property PACKAGE_PIN D12 [get_ports {ADC_Data[2]}]
set_property PACKAGE_PIN C11 [get_ports {ADC_Data[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports key_rst]
set_property IOSTANDARD LVCMOS33 [get_ports key_mode]
set_property IOSTANDARD LVCMOS33 [get_ports key_fun]
set_property PACKAGE_PIN D14 [get_ports key_mode]
set_property PACKAGE_PIN M4 [get_ports key_fun]
set_property PACKAGE_PIN D14 [get_ports key_rst]


set_property PACKAGE_PIN M4 [get_ports key_rst]
